// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDeCI-8-yRYXB-s33mexk5NqlnBcJVEP0I",
    authDomain: "loginnnn-app.firebaseapp.com",
    projectId: "loginnnn-app",
    storageBucket: "loginnnn-app.firebasestorage.app",
    messagingSenderId: "94420079870",
    appId: "1:94420079870:web:e9d9f4b131418068bf41af",
    measurementId: "G-PCPVYHEKQ0",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2C8O3vrmdNqI_uZ7CiU0dzNNJA9Xit5Y',
    appId: '1:94420079870:android:9a9d4fef14748809bf41af',
    messagingSenderId: '94420079870',
    projectId: 'loginnnn-app',
    storageBucket: 'loginnnn-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALxPUosnMXeTSz7hY1lj2RFZHdtxBuZBo',
    appId: '1:94420079870:ios:d8a39f5fadbb742abf41af',
    messagingSenderId: '94420079870',
    projectId: 'loginnnn-app',
    storageBucket: 'loginnnn-app.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALxPUosnMXeTSz7hY1lj2RFZHdtxBuZBo',
    appId: '1:94420079870:ios:d8a39f5fadbb742abf41af',
    messagingSenderId: '94420079870',
    projectId: 'loginnnn-app',
    storageBucket: 'loginnnn-app.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyD2C8O3vrmdNqI_uZ7CiU0dzNNJA9Xit5Y",
    appId: "1:94420079870:windows:e9d9f4b131418068bf41af",
    messagingSenderId: "94420079870",
    projectId: "loginnnn-app",
    storageBucket: "loginnnn-app.firebasestorage.app",
  );
}
